name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Prepare invironment
      run: |
        cp .env.example .env
        cp storage/errors.example storage/errors
        cp storage/titles.example storage/titles

    - name: Get dependencies
      run: go mod vendor

    - name: Run tests
      run: go test ./...

